In [ ]:
import torch
import numpy as np


In [ ]:
x = torch.empty(3,3)
print(x)

x = torch.rand(2,3)
print(x)

x = torch.zeros(5,3, dtype=torch.int)
print(x)
print(x.size())

tensor([[1.7779e-34, 0.0000e+00, 1.7852e-01],
        [1.6761e-02, 1.8498e-01, 8.4557e-01],
        [1.0948e+21, 9.2868e-04, 1.3556e-19]])
tensor([[0.6505, 0.7084, 0.3013],
        [0.0436, 0.7581, 0.1409]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.Size([5, 3])


In [ ]:
x = torch.tensor([2.5,3.1])
print(x)


tensor([2.5000, 3.1000])


In [ ]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)
print()
print(x+y)
print(torch.add(x,y))
print(torch.sub(x,y))
print(torch.mul(x,y))

tensor([[0.8168, 0.4757, 0.4896],
        [0.7224, 0.8774, 0.5859]])
tensor([[0.2387, 0.8087, 0.9070],
        [0.3981, 0.7921, 0.1247]])

tensor([[1.0555, 1.2844, 1.3966],
        [1.1205, 1.6695, 0.7106]])
tensor([[1.0555, 1.2844, 1.3966],
        [1.1205, 1.6695, 0.7106]])
tensor([[ 0.5781, -0.3329, -0.4174],
        [ 0.3242,  0.0853,  0.4611]])
tensor([[0.1950, 0.3847, 0.4441],
        [0.2876, 0.6950, 0.0731]])


In [ ]:
print(y.add_(x))

tensor([[1.4302, 1.5794, 0.8989],
        [0.7849, 0.3151, 1.4578]])


In [ ]:
print(x.view(6))

tensor([0.8168, 0.4757, 0.4896, 0.7224, 0.8774, 0.5859])


In [ ]:
a=torch.ones(5)
print(a)
b=a.numpy()
b

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


not to share memory is down below

In [ ]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
b

[1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
if (torch.cuda.is_available()):
  print("Cuda is available")
  device = torch.device("cuda")
  x = torch.ones(4, device=device)
  y = torch.ones(4)
  y=y.to(device)
  z=x+y
  z=z.to("cpu")
  x=torch.ones(5,requires_grad=True)
  print(x)