# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [ ]:
%matplotlib inline
import torch
import numpy as np

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [ ]:
data = [[-4., -3., -2., -6., -5., -2., -3., -4.],
[-1., -1., -1., -1., -1., -1., -1., -1.],
[0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0.],
[1., 1., 1., 1., 1., 1., 1., 1.],
[4., 3., 2., 6., 5., 2., 3., 4.]]
x_data = torch.tensor(data)
x_data

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
tensor1 = torch.arange(2, 21, 2)
tensor2 = torch.arange(3, 22, 2)
res = torch.mul(tensor1,tensor2)
print(tensor1)
print(tensor2)
print(res)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
tensor([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])
tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])


1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
arr = np.array([])
for x in range(11):
  for y in range(1,8):
    k = x*10+y
    arr = np.append(arr, k)
tensor  = torch.from_numpy(arr).reshape(11,7)
tensor = torch.arange(1,111).reshape(11,10)
tensor [0:11, 0:7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [ ]:
def df(m,n):
  t1 = torch.tensor(([0, 1], [2, 3]))
  t2 = torch.tile(t1, (m, n))
  print(t2[0:m, 0:n])
df(4,5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])


1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [ ]:
ara = torch.FloatTensor(4, 7).uniform_(0, 20)
fin_arr = (ara - ara.min())/(ara.max() - ara.min())
print (fin_arr)

tensor([[0.1912, 0.6581, 0.9400, 0.2732, 0.6144, 0.3206, 0.7450],
        [0.4005, 0.9627, 0.3091, 0.3252, 0.2470, 0.2951, 0.8105],
        [0.9349, 0.7629, 0.2778, 0.6806, 0.2500, 0.6725, 0.5514],
        [0.5024, 0.4104, 0.5054, 0.0000, 0.0985, 0.1643, 1.0000]])


1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [ ]:
ar1 = torch.randint(0, 10, (4,7))
ar2 = torch.randint(0, 10, (4,7))
torch.where(ar1 > ar2, ar1, ar2)

tensor([[3, 4, 6, 3, 6, 8, 3],
        [5, 7, 8, 6, 4, 6, 2],
        [9, 5, 5, 9, 6, 9, 9],
        [9, 3, 5, 4, 7, 4, 6]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [ ]:
t7 = torch.randint(0, 100, (20,))
max_el, max_idx = torch.max(t7, dim=0)
t7[max_idx] = torch.min(t7)

max_el, max_idx = torch.max(t7, dim=0)
print(max_el)
print(max_idx)

tensor(83)
tensor(4)


## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [ ]:
arr_1 = torch.arange(1, 8)
arr_2 = torch.arange(1, 110, 10).view(11,1)
tensor = torch.arange(1,111).reshape(11,10)
tensor [0:11, 0:7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

a_2d_new = torch.transpose(a_2d, 0, 1)
a_2d_new - b_1d


tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

In [ ]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
torch.reshape(torch.argwhere((b-a) == 0), (-1,))

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
torch.flip(torch.arange(9).view(3,3), [0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [ ]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
print(a[(a > 5) & (a <= 10)])

tensor([ 6,  9, 10])


1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [ ]:
a = torch.arange(9).reshape(3,3)
res=torch.transpose(a, 0, 1)
res[[0, 1]] = res[[1, 0]]
print(res.T)

tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])


1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
max,min=10,0
a = (max-min)*torch.rand(8, 10)+min
a

tensor([[3.7799, 7.2520, 4.4627, 0.9518, 7.8323, 3.5959, 6.3796, 9.4199, 8.7018,
         1.5165],
        [3.5629, 3.3920, 2.3944, 3.0368, 2.3967, 5.6625, 1.2875, 0.4979, 9.8486,
         2.0434],
        [0.2721, 8.0251, 6.8454, 4.4685, 2.5095, 1.8313, 5.1734, 4.1903, 6.5197,
         2.9878],
        [0.5460, 4.6150, 0.0316, 9.1192, 3.9122, 6.7170, 6.2507, 3.0207, 5.5798,
         0.7127],
        [8.6704, 1.0118, 6.1068, 7.9595, 4.4834, 0.1459, 1.0279, 0.1375, 3.9757,
         9.7111],
        [6.1662, 5.5747, 7.9005, 9.1886, 1.1512, 8.1998, 8.4228, 5.4790, 4.4624,
         1.1653],
        [0.1002, 0.5427, 0.4217, 3.3558, 3.6586, 0.9607, 6.7094, 7.7793, 2.1335,
         5.1306],
        [7.1564, 3.2868, 2.3910, 0.3288, 2.0738, 3.7160, 9.0709, 0.6980, 7.4031,
         5.2707]])

In [ ]:
var = []
min_val=10000
min_index=None
for i in a:
  var.append(sum(i))

for i in range(len(var)):
  if (min_val>var[i]):
    min_val=var[i]
    min_index=i

print ("Index: ", min_index,"\nElement: ", min_val,"\nThis array: ", a[min_index])

Index:  6 
Element:  tensor(30.7924) 
This array:  tensor([0.1002, 0.5427, 0.4217, 3.3558, 3.6586, 0.9607, 6.7094, 7.7793, 2.1335,
        5.1306])


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
max,min=100,0
a=(max-min)*torch.rand(20)+min
print(a)
print(a[(30 > 5) & (a < 70)])

tensor([86.6165, 29.5186, 21.1912, 29.3863, 68.3245, 22.7001, 49.7613, 16.7737,
        41.9228,  6.2247, 48.7259, 44.1430, 89.8985, 94.7036, 50.2584, 17.1486,
        10.0343, 42.5873, 27.5701, 40.8825])
tensor([29.5186, 21.1912, 29.3863, 68.3245, 22.7001, 49.7613, 16.7737, 41.9228,
         6.2247, 48.7259, 44.1430, 50.2584, 17.1486, 10.0343, 42.5873, 27.5701,
        40.8825])


1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
max,min=10,0
a=(max-min)*torch.rand(30,3)+min
b=(max-min)*torch.rand(30,3)+min
print(a)
print(b)
lis=[]

tensor([[2.3051, 0.2636, 9.4077],
        [2.1597, 6.9110, 9.9134],
        [7.6013, 3.1799, 2.7438],
        [1.8374, 9.3525, 5.5704],
        [8.3657, 8.8512, 6.6665],
        [8.7006, 4.3117, 1.2462],
        [7.7318, 0.3513, 9.2328],
        [7.9026, 1.4300, 8.5054],
        [9.6197, 8.5264, 4.5735],
        [7.6289, 0.3150, 5.4896],
        [8.4807, 3.2643, 5.6148],
        [1.9760, 1.1221, 9.4090],
        [2.7695, 6.2820, 0.9908],
        [2.0607, 4.6091, 5.9998],
        [9.8870, 1.6502, 8.9580],
        [1.5529, 2.5638, 0.5148],
        [2.7868, 8.1338, 7.2378],
        [2.7184, 3.5159, 4.0504],
        [2.7371, 1.9576, 0.9375],
        [1.8117, 5.9365, 1.8405],
        [8.9074, 0.2230, 7.6565],
        [2.5189, 3.2916, 9.0452],
        [3.9275, 6.2072, 6.7885],
        [0.5356, 1.9182, 4.8171],
        [0.4326, 3.2967, 1.4153],
        [2.3416, 4.9678, 5.7187],
        [0.8465, 4.2376, 2.9813],
        [4.6791, 0.8445, 4.0372],
        [9.2207, 4.8783, 1.2857],
        [1.433

In [ ]:
for i in (range(30)):
  for j in (range(3)):
    if (a[i,j]>b[i,j]):
      lis.append(a[i,j])
sum(lis)

tensor(257.0756)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
var=[]
max,min=10,0
a=(max-min)*torch.rand(20,20)+min
a

tensor([[7.8404e-03, 9.0692e+00, 7.2653e+00, 5.5925e+00, 6.1261e-01, 3.1386e+00,
         3.9282e+00, 5.2036e+00, 4.3473e+00, 7.7331e+00, 3.9262e+00, 4.6878e+00,
         6.8288e+00, 6.5994e+00, 8.0532e+00, 1.2658e+00, 1.3943e+00, 5.5637e+00,
         6.7236e-02, 5.7390e+00],
        [3.4385e+00, 1.7082e+00, 5.0195e+00, 8.9607e+00, 1.2919e+00, 5.4779e+00,
         4.4169e+00, 2.7527e-01, 1.2579e+00, 5.5357e+00, 4.0591e-01, 2.3580e+00,
         4.4523e+00, 7.2514e+00, 8.6533e+00, 9.5175e+00, 1.6698e+00, 7.7684e-01,
         2.2127e+00, 4.9838e+00],
        [8.8573e+00, 9.0315e-01, 4.2277e+00, 9.4569e+00, 8.1198e+00, 6.9544e+00,
         6.4850e+00, 3.2364e+00, 4.4784e+00, 6.0768e+00, 8.2546e+00, 5.1003e-01,
         2.1086e+00, 1.8938e+00, 3.7199e-01, 9.8663e+00, 8.0271e+00, 8.5572e-01,
         4.2998e+00, 3.9923e+00],
        [5.7815e+00, 4.0289e-01, 9.4321e+00, 7.6293e-01, 4.6804e+00, 7.8242e+00,
         3.4309e+00, 3.9367e+00, 6.3978e+00, 8.6924e-01, 9.3758e+00, 1.7754e+00,
       

In [ ]:
for i in range(20):
  for j in range(20):
    if (i==j and j+1<=19):
      var.append(a[i,j+1])

print(var)

[tensor(9.0692), tensor(5.0195), tensor(9.4569), tensor(4.6804), tensor(6.6793), tensor(9.8401), tensor(5.0888), tensor(6.3622), tensor(4.4663), tensor(4.5426), tensor(1.9831), tensor(7.5284), tensor(7.9406), tensor(2.9760), tensor(5.1154), tensor(5.0198), tensor(7.2792), tensor(9.7605), tensor(5.7928)]


1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
ar1 = torch.randint(0, 10, (5,10))
ar2 = torch.randint(0, 10, (5,10))
ar1

tensor([[7, 1, 3, 3, 5, 9, 0, 1, 3, 4],
        [8, 3, 7, 9, 9, 2, 9, 8, 3, 1],
        [0, 3, 5, 3, 2, 8, 3, 3, 2, 7],
        [1, 9, 1, 3, 9, 0, 8, 1, 0, 5],
        [1, 7, 4, 2, 1, 9, 6, 9, 4, 8]])

In [ ]:
for i in range(5):
  for j in range(10):
    if (ar1[i,j]==ar2[i,j]):
      ar1[i,j]=ar1[i,j]*2
ar1

tensor([[ 7,  1,  3,  3,  5,  9,  0,  1,  3,  4],
        [ 8,  3, 14,  9,  9,  2, 18,  8,  3,  1],
        [ 0,  3,  5,  3,  2,  8,  3,  6,  2,  7],
        [ 1,  9,  1,  3,  9,  0,  8,  1,  0,  5],
        [ 1,  7,  4,  2,  2,  9,  6,  9,  4,  8]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
ar1 = torch.randint(0, 10, (4,7))
ar2 = torch.randint(0, 10, (4,7))
ar3 = torch.randint(0, 10, (4,7))
print(ar1)
print("\n")
print(ar2)
print("\n")
print(ar3)

tensor([[1, 4, 0, 2, 3, 7, 5],
        [0, 7, 2, 3, 2, 5, 2],
        [6, 6, 9, 5, 7, 4, 0],
        [2, 4, 3, 9, 6, 0, 0]])


tensor([[4, 5, 0, 3, 7, 0, 7],
        [5, 8, 4, 0, 2, 8, 4],
        [7, 6, 1, 4, 8, 7, 6],
        [9, 5, 0, 8, 4, 4, 4]])


tensor([[0, 0, 9, 3, 0, 2, 0],
        [7, 7, 8, 7, 7, 9, 7],
        [1, 0, 7, 6, 5, 7, 8],
        [9, 1, 5, 4, 7, 2, 4]])


In [ ]:
for i in range(4):
  for j in range(7):
    if (ar1[i,j]>ar2[i,j] and ar1[i,j]<ar3[i,j]):
      ar1[i,j]=0

ar1

tensor([[1, 4, 0, 2, 3, 7, 5],
        [0, 7, 2, 0, 2, 5, 2],
        [6, 6, 9, 0, 7, 4, 0],
        [2, 4, 0, 9, 0, 0, 0]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
ar1 = torch.randint(0, 20, (20,5))
ar1=ar1.T
ar1

tensor([[17,  1, 13,  4,  0, 16,  4, 15, 10, 10,  3,  2, 11,  2,  3, 15,  1,  9,
          3, 11],
        [ 0, 14,  4, 12, 17,  6, 12,  6,  1,  5,  5, 17, 19, 14,  9, 13, 17,  3,
         19,  8],
        [17,  1, 14, 19,  7,  6, 16, 12,  6,  4,  6, 15,  0,  1, 12,  6, 17,  9,
          1, 16],
        [ 0, 15, 14,  3,  9, 13,  8, 17, 18,  4,  4, 17,  6,  8, 18, 17, 12,  8,
          7, 19],
        [16, 11,  7,  5,  3, 13, 15,  1, 16,  2, 10, 14, 19,  7, 18, 12, 16, 11,
         15,  5]])

In [ ]:
for i in range(5):
  maximum_val = torch.max(ar1[i])
  iter=0
  for j in range(20):
    if (ar1[i,j]==maximum_val):
      iter+=1
      if (iter==2):
        print(f"MAX VALUE IN {i} column")

MAX VALUE IN 1 column


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [ ]:
max,min=1,0
ar1=(max-min)*torch.rand(4,7)+min
ar1

tensor([[0.9903, 0.7765, 0.0651, 0.4153, 0.1399, 0.2765, 0.6758],
        [0.8307, 0.1339, 0.0099, 0.2575, 0.3218, 0.1774, 0.6560],
        [0.0024, 0.6994, 0.3669, 0.4113, 0.4875, 0.4492, 0.6123],
        [0.8584, 0.9161, 0.0198, 0.2495, 0.3848, 0.5088, 0.1414]])

In [ ]:
for i in range(4):
  max_value = torch.max(ar1[i])
  print(max_value)
  it=False
  for j in range(7):
    if (ar1[i,j]!=max_value and it):
      ar1[i,j]=0
    else:
      it=True

ar1

tensor(0.9903)
tensor(0.8307)
tensor(0.6994)
tensor(0.9161)


tensor([[0.9903, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8307, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0024, 0.6994, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8584, 0.9161, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [ ]:
max,min=100,0
ar1 = torch.randint(0, 100, (1,100))[0]
ar1

tensor([ 9, 36, 10, 35, 48, 60, 18, 54, 35, 28, 87, 63, 21, 85, 29,  2, 70, 78,
        81, 88, 62, 19, 71, 32, 95,  4, 27, 28, 56,  6, 48, 13, 73,  4, 99, 27,
        40, 25, 14, 39,  6, 94, 88, 36, 13, 78, 75, 84, 93, 56, 65, 98, 90, 44,
        33, 89,  9, 51, 53, 53, 36, 65,  4, 71,  3,  8, 95, 52, 35, 91, 55, 22,
        24, 93, 44, 70, 84, 21, 11, 24, 32, 79, 72, 52, 49,  9, 54, 68, 30, 83,
        45, 36, 76,  0, 42, 71, 93, 56, 63, 82])

In [ ]:
torch.mode(ar1,0)

torch.return_types.mode(
values=tensor(36),
indices=tensor(43))

In [ ]:
import numpy
import operator
fdist=dict(zip(*numpy.unique(ar1, return_counts=True)))

print("The elements with their counts are -", fdist)
print("The most common word is -",list(fdist)[-1])

The elements with their counts are - {0: 1, 2: 1, 3: 1, 4: 3, 6: 2, 8: 1, 9: 3, 10: 1, 11: 1, 13: 2, 14: 1, 18: 1, 19: 1, 21: 2, 22: 1, 24: 2, 25: 1, 27: 2, 28: 2, 29: 1, 30: 1, 32: 2, 33: 1, 35: 3, 36: 4, 39: 1, 40: 1, 42: 1, 44: 2, 45: 1, 48: 2, 49: 1, 51: 1, 52: 2, 53: 2, 54: 2, 55: 1, 56: 3, 60: 1, 62: 1, 63: 2, 65: 2, 68: 1, 70: 2, 71: 3, 72: 1, 73: 1, 75: 1, 76: 1, 78: 2, 79: 1, 81: 1, 82: 1, 83: 1, 84: 2, 85: 1, 87: 1, 88: 2, 89: 1, 90: 1, 91: 1, 93: 3, 94: 1, 95: 2, 98: 1, 99: 1}
The most common word is - 99


In [ ]:
#One more method

sorted_tuples = sorted(fdist.items(), key=operator.itemgetter(1),reverse=True)
sorted_dict = {k: v for k, v in sorted_tuples}
print(sorted_dict)

{36: 4, 4: 3, 9: 3, 35: 3, 56: 3, 71: 3, 93: 3, 6: 2, 13: 2, 21: 2, 24: 2, 27: 2, 28: 2, 32: 2, 44: 2, 48: 2, 52: 2, 53: 2, 54: 2, 63: 2, 65: 2, 70: 2, 78: 2, 84: 2, 88: 2, 95: 2, 0: 1, 2: 1, 3: 1, 8: 1, 10: 1, 11: 1, 14: 1, 18: 1, 19: 1, 22: 1, 25: 1, 29: 1, 30: 1, 33: 1, 39: 1, 40: 1, 42: 1, 45: 1, 49: 1, 51: 1, 55: 1, 60: 1, 62: 1, 68: 1, 72: 1, 73: 1, 75: 1, 76: 1, 79: 1, 81: 1, 82: 1, 83: 1, 85: 1, 87: 1, 89: 1, 90: 1, 91: 1, 94: 1, 98: 1, 99: 1}


In [ ]:
#another method
from collections import Counter
x=Counter(ar1)
dict(sorted(x.items(), key=lambda item: item[1]))

{tensor(9): 1,
 tensor(36): 1,
 tensor(10): 1,
 tensor(35): 1,
 tensor(48): 1,
 tensor(60): 1,
 tensor(18): 1,
 tensor(54): 1,
 tensor(35): 1,
 tensor(28): 1,
 tensor(87): 1,
 tensor(63): 1,
 tensor(21): 1,
 tensor(85): 1,
 tensor(29): 1,
 tensor(2): 1,
 tensor(70): 1,
 tensor(78): 1,
 tensor(81): 1,
 tensor(88): 1,
 tensor(62): 1,
 tensor(19): 1,
 tensor(71): 1,
 tensor(32): 1,
 tensor(95): 1,
 tensor(4): 1,
 tensor(27): 1,
 tensor(28): 1,
 tensor(56): 1,
 tensor(6): 1,
 tensor(48): 1,
 tensor(13): 1,
 tensor(73): 1,
 tensor(4): 1,
 tensor(99): 1,
 tensor(27): 1,
 tensor(40): 1,
 tensor(25): 1,
 tensor(14): 1,
 tensor(39): 1,
 tensor(6): 1,
 tensor(94): 1,
 tensor(88): 1,
 tensor(36): 1,
 tensor(13): 1,
 tensor(78): 1,
 tensor(75): 1,
 tensor(84): 1,
 tensor(93): 1,
 tensor(56): 1,
 tensor(65): 1,
 tensor(98): 1,
 tensor(90): 1,
 tensor(44): 1,
 tensor(33): 1,
 tensor(89): 1,
 tensor(9): 1,
 tensor(51): 1,
 tensor(53): 1,
 tensor(53): 1,
 tensor(36): 1,
 tensor(65): 1,
 tensor(4): 1,


## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
import math
for i in range(10):
  if(i*math.sin(i)>0.5):
    print(f"Value {i} is greater than 0.5 ",i*math.sin(i) )

Value 1 is greater than 0.5  0.8414709848078965
Value 2 is greater than 0.5  1.8185948536513634
Value 7 is greater than 0.5  4.598906191031523
Value 8 is greater than 0.5  7.914865972987054
Value 9 is greater than 0.5  3.7090663671758093


1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
a, n = True, int(100) #n - число, до которого хотим дойти
for x in range(1,n):
    for y in range(1,n):
        if x != y and y != 1:
            if not x % y:
                a = False
                break
    if a == True:
        print(x,end=' ')
    a = True

1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
x = torch.tensor([2, 3, 4, 5, 6, 7, 8, 9, 10])
y = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

res = ((x - y) ** 2).sum().item()
res



9

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
arr = torch.randint(0, 101, size=[20, 3])
mask = (arr ** 2).sum(axis=1).sort().indices
res = arr[mask]
res



tensor([[  9,  30,  29],
        [ 31,   3,  48],
        [ 15,   3,  65],
        [ 24,  33,  58],
        [  1,  55,  50],
        [ 51,   3,  57],
        [  3,  50,  67],
        [  2,  26,  84],
        [ 23,   3,  92],
        [ 46,  27,  79],
        [ 82,  50,  21],
        [ 67,  66,  39],
        [ 82,   7,  60],
        [ 58,  80,  42],
        [ 89,  55,  25],
        [ 59,  64,  83],
        [ 98,  78,   7],
        [ 56,  98,  67],
        [ 92,  45,  92],
        [ 58,  77, 100]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
arr =  torch.rand(100)
index = (np.abs(arr-10)).argmin()
print(arr[index])

tensor(0.9988)


1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 